blueprint:
  name: Lux Motion Lights
  description: Turn on lights when motion and Lux is below a certain amount.
  domain: automation
  author: Dan Clayton

  input:
    light_target:
      name: Lights
      selector:
        target:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain:
            - binary_sensor
          device_class: motion
    duration:
      name: Duration
      selector:
        duration:

trigger:
  - platform: state
    entity_id:
      - !input motion_entity
    to: "on"
condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.home_solar_rad_lx
        below: 20000
      - condition: time
        after: "06:00:00"
        before: "21:30:00"
action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target: !input light_target
  - wait_for_trigger:
      - platform: state
        entity_id:
          - binary_sensor.living_room_motion_motion
        to: "off"
        for: !input duration
  - service: light.turn_off
    metadata: {}
    data: {}
    target: !input light_target
mode: single
